name: Push to MarcusYYDS/open-bmclapi-dashboard

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Commit files
        run: |
          git config --local user.email "marcus@marcus233.top"
          git config --local user.name "MarcusYYDS"
          git push --force --quiet "https://MarcusYYDS:${{ secrets.GITHUBTOKEN }}@github.com/MarcusYYDS/OpenBMCLAPI-Dashboard.git" main:main